Error:


Calculating PDs (input for PH)...
PH


Tuning the hyperparameters...
Tuning the hyperparameters with GridSearchCV() ...
Runtime =  2.1  seconds.
    rank                                              param   avg acc
2      1  {'PH': FunctionTransformer(func=<function sort...  0.899810
8      2  {'PH': PersistenceImage(im_range=[0, 2, 0, 2],...  0.888414
5      3  {'PH': PersistenceImage(im_range=[0, 2, 0, 2],...  0.850427
11     4  {'PH': PersistenceImage(im_range=[0, 2, 0, 2],...  0.838557
44     5  {'PH': Landscape(sample_range=[0, 2]), 'PH__nu...  0.838082
47     6  {'PH': Landscape(sample_range=[0, 2]), 'PH__nu...  0.825261
1      7  {'PH': FunctionTransformer(func=<function sort...  0.800570
17     8  {'PH': PersistenceImage(im_range=[0, 2, 0, 2],...  0.775878
41     9  {'PH': Landscape(sample_range=[0, 2]), 'PH__nu...  0.749763
26    10  {'PH': PersistenceImage(im_range=[0, 2, 0, 2],...  0.738841
Best parameters: {'PH': FunctionTransformer(func=<function sorted_lifespans_pds at 0x120e84180>), 'PH__func': <function sorted_lifespans_pds at 0x120e84180>, 'classifier': SVC(C=100), 'classifier__C': 100}
Best accuracy =  0.8998100664767331


Training...
Saving data to file...
Data saved to file debug_dict__20240522_121131.json.


Calculating accuracy...
Traceback (most recent call last):
  File "/Users/nan/Documents/PhD/research/TDA/gudhi/ellipsoids/src/turkevs_holes_experiment.py", line 274, in <module>
    run_experiments(data_folder, path_results)
  File "/Users/nan/Documents/PhD/research/TDA/gudhi/ellipsoids/src/turkevs_holes_experiment.py", line 204, in run_experiments
    accs["PH"] = calculate_accuracy_trnsfs(ph_ml, data_pd_train, labels_train, data_pd_test_trnsfs, labels_test, TRAIN_SIZES, results_path=results_path, name='PH')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nan/Documents/PhD/research/TDA/gudhi/ellipsoids/src/turkevs_holes_experiment.py", line 97, in calculate_accuracy_trnsfs
    acc = model.get_score(data_test_trnsfs['std'], labels_test, model_trained) # new
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nan/Documents/PhD/research/TDA/gudhi/ellipsoids/src/model.py", line 46, in get_score
    score_test = model.score(data_test, labels_test)  
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/pipeline.py", line 753, in score
    return self.steps[-1][1].score(Xt, y, **score_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/base.py", line 705, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/svm/_base.py", line 818, in predict
    y = super().predict(X)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/svm/_base.py", line 431, in predict
    X = self._validate_for_predict(X)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/svm/_base.py", line 611, in _validate_for_predict
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/base.py", line 625, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/usr/local/lib/python3.11/site-packages/sklearn/base.py", line 414, in _check_n_features
    raise ValueError(
ValueError: X has 78 features, but SVC is expecting 85 features as input.
nan@nan-comp ellipsoids % 